import _ from 'lodash';

const countries = [
    {name: 'kYiv', country: '  ukraInE' },
    {name: 'Odessa ', country: 'ukraInE' },  
    {name: 'gdYNia ', country: 'PolaNd' },
    {name: 'kraKoW ', country: 'polAnd' },
    {name: 'Herat', country: 'Afghanistan'},
    {name: 'Kabul', country: 'Afghanistan'},
    {name: 'Kandahar', country: 'Afghanistan'},
    {name: 'Molah', country: 'Afghanistan'},
    {name: 'Rana', country: 'Afghanistan'},
    {name: 'Shar', country: 'Afghanistan'},
    {name: 'Sharif', country: 'Afghanistan'},
    {name: 'Wazir Akbar Khan', country: 'Afghanistan'},
    {name: 'Elbasan', country: 'Albania'},
    {name: 'Petran', country: 'Albania'},
    {name: 'Pogradec', country: 'Albania'},
    {name: 'Shkoder', country: 'Albania'},
    {name: 'Tirana', country: 'Albania'},
    {name: 'Ura Vajgurore', country: 'Albania'},
    {name: 'Andorra la Vella', country: 'Andorra'},
    {name: 'Canillo', country: 'Andorra'},
    {name: 'Encamp', country: 'Andorra'},
    {name: 'Engordany', country: 'Andorra'},
    {name: 'Escaldes-Engordany', country: 'Andorra'},
    {name: 'La Massana', country: 'Andorra'},
    {name: 'Llorts', country: 'Andorra'},
    {name: 'Ordino', country: 'Andorra'},
    {name: 'Santa Coloma', country: 'Andorra'},
    {name: 'Sispony', country: 'Andorra'},
    {name: 'Soldeu', country: 'Andorra'},
    {name: 'All Saints', country: 'Antigua and Barbuda'},
    {name: 'Cassada Gardens', country: 'Antigua and Barbuda'},
    {name: 'Codrington', country: 'Antigua and Barbuda'},
    {name: 'Old Road', country: 'Antigua and Barbuda'},
    {name: 'Parham', country: 'Antigua and Barbuda'},
    {name: 'Woods', country: 'Antigua and Barbuda'},
    {name: 'Abovyan', country: 'Armenia'},
    {name: 'Agarak', country: 'Armenia'},
    {name: 'Apaga', country: 'Armenia'},
    {name: 'Aparan', country: 'Armenia'},
    {name: 'Arabkir', country: 'Armenia'},
    {name: 'Ashtarak', country: 'Armenia'},
    {name: 'Erebuni Fortress', country: 'Armenia'},
    {name: 'Hrazdan', country: 'Armenia'},
    {name: 'Ijevan', country: 'Armenia'},
    {name: 'Jermuk', country: 'Armenia'},
    {name: 'Kapan', country: 'Armenia'},
    {name: 'Tsaghkadzor', country: 'Armenia'},
    {name: 'Vanadzor', country: 'Armenia'},
    {name: 'Yerevan', country: 'Armenia'},
    {name: 'Noord', country: 'Aruba'},
    {name: 'Oranjestad', country: 'Aruba'},
    {name: 'Palm Beach', country: 'Aruba'},
    {name: 'Paradera', country: 'Aruba'},
    {name: 'Ponton', country: 'Aruba'},
    {name: 'Sabaneta', country: 'Aruba'},
    {name: 'San Barbola', country: 'Aruba'},
    {name: 'Santa Cruz', country: 'Aruba'},
    {name: 'Sero Blanco', country: 'Aruba'},
    {name: 'Sint Nicolaas', country: 'Aruba'},
    {name: 'Tanki Lender', country: 'Aruba'},
    {name: 'Baku', country: 'Azerbaijan'},
    {name: 'Nakhchivan', country: 'Azerbaijan'},
    {name: 'Quba', country: 'Azerbaijan'},
    {name: 'Qusar', country: 'Azerbaijan'},
    {name: 'Sulutapa', country: 'Azerbaijan'},
    {name: 'Sumqayit', country: 'Azerbaijan'},
    {name: 'Xirdalan', country: 'Azerbaijan'},
    {name: 'Zurges', country: 'Azerbaijan'},
    {name: 'Andros Town', country: 'Bahamas'},
    {name: 'Dunmore Town', country: 'Bahamas'},
    {name: 'Freeport', country: 'Bahamas'},
    {name: 'Marsh Harbour', country: 'Bahamas'},
    {name: 'Nassau', country: 'Bahamas'},
    {name: 'Palmetto Point', country: 'Bahamas'},
    {name: 'Spanish Wells', country: 'Bahamas'},
    {name: 'Al Budayyi`', country: 'Bahrain'},
    {name: 'Al Hadd', country: 'Bahrain'},
    {name: 'Al Hamalah', country: 'Bahrain'},
    {name: 'Al Janabiyah', country: 'Bahrain'},
    {name: 'Al Markh', country: 'Bahrain'},
    {name: 'Al Muharraq', country: 'Bahrain'},
    {name: 'Bani Jamrah', country: 'Bahrain'},
    {name: 'Barbar', country: 'Bahrain'},
    {name: 'Jurdab', country: 'Bahrain'},
    {name: 'Madinat `Isa', country: 'Bahrain'},
    {name: 'Madinat Hamad', country: 'Bahrain'},
    {name: 'Manama', country: 'Bahrain'},
    {name: 'Oil City', country: 'Bahrain'},
    {name: 'Sanabis', country: 'Bahrain'},
    {name: 'Sanad', country: 'Bahrain'},
    {name: 'Sitrah', country: 'Bahrain'},
    {name: 'Tubli', country: 'Bahrain'},
    {name: 'Agrabad', country: 'Bangladesh'},
    {name: 'Bangla', country: 'Bangladesh'},
    {name: 'Barisal', country: 'Bangladesh'},
    {name: 'Bazar', country: 'Bangladesh'},
    {name: 'Chittagong', country: 'Bangladesh'},
    {name: 'Comilla', country: 'Bangladesh'},
    {name: 'Delta', country: 'Bangladesh'},
    {name: 'Dhaka', country: 'Bangladesh'},
    {name: 'Hossain', country: 'Bangladesh'},
    {name: 'Jessore', country: 'Bangladesh'},
    {name: 'Kabi', country: 'Bangladesh'},
    {name: 'Kazipur', country: 'Bangladesh'},
    {name: 'Mymensingh', country: 'Bangladesh'},
    {name: 'Narayanganj', country: 'Bangladesh'},
    {name: 'Rajshahi', country: 'Bangladesh'},
    {name: 'Tejgaon', country: 'Bangladesh'},
    {name: 'Uttara', country: 'Bangladesh'},
    {name: 'Belize City', country: 'Belize'},
    {name: 'Belmopan', country: 'Belize'},
    {name: 'Benque Viejo del Carmen', country: 'Belize'},
    {name: 'Freetown Sibun', country: 'Belize'},
    {name: 'Ladyville', country: 'Belize'},
    {name: 'San Ignacio', country: 'Belize'},
    {name: 'San Pedro Town', country: 'Belize'},
    {name: 'Anillo', country: 'Bolivia'},
    {name: 'Aroma', country: 'Bolivia'},
    {name: 'Bermejo', country: 'Bolivia'},
    {name: 'Caracasa', country: 'Bolivia'},
    {name: 'Cobija', country: 'Bolivia'},
    {name: 'Cochabamba', country: 'Bolivia'},
    {name: 'Cotoca', country: 'Bolivia'},
    {name: 'Cruz', country: 'Bolivia'},
    {name: 'Guayaramerin', country: 'Bolivia'},
    {name: 'La Paz', country: 'Bolivia'},
    {name: 'Oruro', country: 'Bolivia'},
    {name: 'Riberalta', country: 'Bolivia'},
    {name: 'Santa Cruz', country: 'Bolivia'},
    {name: 'Santa Cruz', country: 'Bolivia'},
    {name: 'Sucre', country: 'Bolivia'},
    {name: 'Tarija', country: 'Bolivia'},
    {name: 'Trinidad', country: 'Bolivia'},
    {name: 'Francistown', country: 'Botswana'},
    {name: 'Gaborone', country: 'Botswana'},
    {name: 'Orapa', country: 'Botswana'},
    {name: 'Serowe', country: 'Botswana'},
    {name: 'Village', country: 'Botswana'},
    {name: 'Bandar Seri Begawan', country: 'Brunei'},
    {name: 'Bangar', country: 'Brunei'},
    {name: 'Kampong Jerudong', country: 'Brunei'},
    {name: 'Kuala Balai', country: 'Brunei'},
    {name: 'Kuala Belait', country: 'Brunei'},
    {name: 'Panaga', country: 'Brunei'},
    {name: 'Seria', country: 'Brunei'},
    {name: 'Tutong', country: 'Brunei'},
    {name: 'Moung Roessei', country: 'Cambodia'},
    {name: 'Phnom Penh', country: 'Cambodia'},
    {name: 'Phumi Boeng (1)', country: 'Cambodia'},
    {name: 'Phumi Chhuk', country: 'Cambodia'},
    {name: 'Phumi Preah Haoh', country: 'Cambodia'},
    {name: 'Phumi Prei', country: 'Cambodia'},
    {name: 'Phumi Prek Mrinh', country: 'Cambodia'},
    {name: 'Phumi Siem Reab', country: 'Cambodia'},
    {name: 'Phumi Thmei', country: 'Cambodia'},
    {name: 'Phumi Thnal', country: 'Cambodia'},
    {name: 'Phumi Vott Phnum', country: 'Cambodia'},
    {name: 'Sihanoukville', country: 'Cambodia'},
    {name: 'Tuol Kok', country: 'Cambodia'},
    {name: 'Vott Kampong Svay', country: 'Cambodia'},
    {name: 'Bafia', country: 'Cameroon'},
    {name: 'Bafoussam', country: 'Cameroon'},
    {name: 'Bamenda', country: 'Cameroon'},
    {name: 'Buea', country: 'Cameroon'},
    {name: 'Douala', country: 'Cameroon'},
    {name: 'Kribi', country: 'Cameroon'},
    {name: 'Kumba', country: 'Cameroon'},
    {name: 'Ringo', country: 'Cameroon'},
    {name: 'Tibati', country: 'Cameroon'},
    {name: 'Bodden Town', country: 'Cayman Islands'},
    {name: 'Coral Gables', country: 'Cayman Islands'},
    {name: 'George Town', country: 'Cayman Islands'},
    {name: 'Newlands', country: 'Cayman Islands'},
    {name: 'Savannah', country: 'Cayman Islands'},
    {name: 'Spot Bay', country: 'Cayman Islands'},
    {name: 'West Bay', country: 'Cayman Islands'},
    {name: 'Banana', country: 'Congo'},
    {name: 'Goma', country: 'Congo'},
    {name: 'Kinshasa', country: 'Congo'},
    {name: 'Likasi', country: 'Congo'},
    {name: 'Lubumbashi', country: 'Congo'},
    {name: 'Bayamo', country: 'Cuba'},
    {name: 'Cienfuegos', country: 'Cuba'},
    {name: 'Habana', country: 'Cuba'},
    {name: 'Havana', country: 'Cuba'},
    {name: 'La Habana', country: 'Cuba'},
    {name: 'Las Tunas', country: 'Cuba'},
    {name: 'Matanzas', country: 'Cuba'},
    {name: 'Santiago de Cuba', country: 'Cuba'},
    {name: 'Varadero', country: 'Cuba'},
    {name: 'Villa', country: 'Cuba'},
    {name: 'Argir', country: 'Faroe Islands'},
    {name: 'Glyvrar', country: 'Faroe Islands'},
    {name: 'Hvalba', country: 'Faroe Islands'},
    {name: 'Innan Glyvur', country: 'Faroe Islands'},
    {name: 'Leirvik', country: 'Faroe Islands'},
    {name: 'Saltangara', country: 'Faroe Islands'},
    {name: 'Signabour', country: 'Faroe Islands'},
    {name: 'Strendur', country: 'Faroe Islands'},
    {name: 'Arue', country: 'French Polynesia'},
    {name: 'Faaa', country: 'French Polynesia'},
    {name: 'Mahina', country: 'French Polynesia'},
    {name: 'Paeau', country: 'French Polynesia'},
    {name: 'Papeete', country: 'French Polynesia'},
    {name: 'Pirae', country: 'French Polynesia'},
    {name: 'Punaauia', country: 'French Polynesia'},
    {name: 'Gamba', country: 'Gabon'},
    {name: 'Libreville', country: 'Gabon'},
    {name: 'Mamagnia', country: 'Gabon'},
    {name: 'Moanda', country: 'Gabon'},
    {name: 'Port-Gentil', country: 'Gabon'},
    {name: 'Gogolesubani', country: 'Georgia'},
    {name: 'Kutaisi', country: 'Georgia'},
    {name: 'Lentekhi', country: 'Georgia'},
    {name: 'Qazbegi', country: 'Georgia'},
    {name: 'Samtredia', country: 'Georgia'},
    {name: 'Sukhumi', country: 'Georgia'},
    {name: 'Tbilisi', country: 'Georgia'},
    {name: 'Zemo-Avchala', country: 'Georgia'},
    {name: 'Zugdidi', country: 'Georgia'},
    {name: 'Accra', country: 'Ghana'},
    {name: 'Bawku', country: 'Ghana'},
    {name: 'Berekum', country: 'Ghana'},
    {name: 'Bolgatanga', country: 'Ghana'},
    {name: 'Cape Coast', country: 'Ghana'},
    {name: 'Home', country: 'Ghana'},
    {name: 'Koforidua', country: 'Ghana'},
    {name: 'Kumasi', country: 'Ghana'},
    {name: 'Legon', country: 'Ghana'},
    {name: 'Mampong', country: 'Ghana'},
    {name: 'Navrongo', country: 'Ghana'},
    {name: 'Sunyani', country: 'Ghana'},
    {name: 'Takoradi', country: 'Ghana'},
    {name: 'Tema', country: 'Ghana'},
    {name: 'Wa', country: 'Ghana'},
    {name: 'Winneba', country: 'Ghana'},
    {name: 'Aasiaat', country: 'Greenland'},
    {name: 'Ilulissat', country: 'Greenland'},
    {name: 'Kapisillit', country: 'Greenland'},
    {name: 'Maniitsoq', country: 'Greenland'},
    {name: 'Narsaq', country: 'Greenland'},
    {name: 'Narsarsuaq', country: 'Greenland'},
    {name: 'Nuuk', country: 'Greenland'},
    {name: 'Nuussuaq', country: 'Greenland'},
    {name: 'Paamiut', country: 'Greenland'},
    {name: 'Qaqortoq', country: 'Greenland'},
    {name: 'Qasigiannguit', country: 'Greenland'},
    {name: 'Qeqertarsuaq', country: 'Greenland'},
    {name: 'Qeqertat', country: 'Greenland'},
    {name: 'Sisimiut', country: 'Greenland'},
    {name: 'Tasiilaq', country: 'Greenland'},
    {name: 'Upernavik', country: 'Greenland'},
    {name: 'Uummannaq Kommune', country: 'Greenland'},
    {name: 'Barrigada Village', country: 'Guam'},
    {name: 'Dededo Village', country: 'Guam'},
    {name: 'Inarajan Village', country: 'Guam'},
    {name: 'Santa Rita', country: 'Guam'},
    {name: 'Tamuning-Tumon-Harmon Village', country: 'Guam'},
    {name: 'Yigo Village', country: 'Guam'},
    {name: 'Conakry', country: 'Guinea'},
    {name: 'Dabola', country: 'Guinea'},
    {name: 'Kalia', country: 'Guinea'},
    {name: 'Kankan', country: 'Guinea'},
    {name: 'Lola', country: 'Guinea'},
    {name: 'Mamou', country: 'Guinea'},
    {name: 'Port Kamsar', country: 'Guinea'},
    {name: 'Sangaredi', country: 'Guinea'},
    {name: 'Carrefour', country: 'Haiti'},
    {name: 'Delmar', country: 'Haiti'},
    {name: 'Duverger', country: 'Haiti'},
    {name: 'Jacmel', country: 'Haiti'},
    {name: 'Masseau', country: 'Haiti'},
    {name: 'Moise', country: 'Haiti'},
    {name: 'Petionville', country: 'Haiti'},
    {name: 'Port-au-Prince', country: 'Haiti'},
    {name: 'Prince', country: 'Haiti'},
    {name: 'Turgeau', country: 'Haiti'},
    {name: 'Amman', country: 'Hashemite Kingdom of Jordan'},
    {name: 'Ar Ramtha', country: 'Hashemite Kingdom of Jordan'},
    {name: 'Farah', country: 'Hashemite Kingdom of Jordan'},
    {name: 'Irbid', country: 'Hashemite Kingdom of Jordan'},
    {name: 'Madaba', country: 'Hashemite Kingdom of Jordan'},
    {name: 'Sahab', country: 'Hashemite Kingdom of Jordan'},
    {name: 'Salt', country: 'Hashemite Kingdom of Jordan'},
    {name: 'Choloma', country: 'Honduras'},
    {name: 'Comayagua', country: 'Honduras'},
    {name: 'Comayaguela', country: 'Honduras'},
    {name: 'Coxen Hole', country: 'Honduras'},
    {name: 'El Barro', country: 'Honduras'},
    {name: 'El Paraiso', country: 'Honduras'},
    {name: 'El Progreso', country: 'Honduras'},
    {name: 'La Ceiba', country: 'Honduras'},
    {name: 'La Hacienda', country: 'Honduras'},
    {name: 'Morazan', country: 'Honduras'},
    {name: 'Nacaome', country: 'Honduras'},
    {name: 'Pinalejo', country: 'Honduras'},
    {name: 'Piraera', country: 'Honduras'},
    {name: 'Puerto Lempira', country: 'Honduras'},
    {name: 'San Antonio de Flores', country: 'Honduras'},
    {name: 'San Pedro Sula', country: 'Honduras'},
    {name: 'Santa Barbara', country: 'Honduras'},
    {name: 'Sula', country: 'Honduras'},
    {name: 'Tegucigalpa', country: 'Honduras'},
    {name: 'Akranes', country: 'Iceland'},
    {name: 'Akureyri', country: 'Iceland'},
    {name: 'Borgarnes', country: 'Iceland'},
    {name: 'Dalvik', country: 'Iceland'},
    {name: 'Grindavik', country: 'Iceland'},
    {name: 'Hella', country: 'Iceland'},
    {name: 'Holmavik', country: 'Iceland'},
    {name: 'Husavik', country: 'Iceland'},
    {name: 'Hvammstangi', country: 'Iceland'},
    {name: 'Hveragerdi', country: 'Iceland'},
    {name: 'Hvolsvollur', country: 'Iceland'},
    {name: 'Kopavogur', country: 'Iceland'},
    {name: 'Reykjavik', country: 'Iceland'},
    {name: 'Selfoss', country: 'Iceland'},
    {name: 'Skagastrond', country: 'Iceland'},
    {name: 'Stokkseyri', country: 'Iceland'},
    {name: 'Vestmannaeyjar', country: 'Iceland'},
    {name: 'Vogar', country: 'Iceland'},
    {name: 'Al `Amarah', country: 'Iraq'},
    {name: 'Al Hillah', country: 'Iraq'},
    {name: 'Baghdad', country: 'Iraq'},
    {name: 'Bahr', country: 'Iraq'},
    {name: 'Basere', country: 'Iraq'},
    {name: 'Basra', country: 'Iraq'},
    {name: 'Erbil', country: 'Iraq'},
    {name: 'Haji Hasan', country: 'Iraq'},
    {name: 'Hayat', country: 'Iraq'},
    {name: 'Karkh', country: 'Iraq'},
    {name: 'Kirkuk', country: 'Iraq'},
    {name: 'Manawi', country: 'Iraq'},
    {name: 'Mosul', country: 'Iraq'},
    {name: 'Najaf', country: 'Iraq'},
    {name: 'Sulaymaniyah', country: 'Iraq'},
    {name: 'Tikrit', country: 'Iraq'},
    {name: 'Ballasalla', country: 'Isle of Man'},
    {name: 'Castletown', country: 'Isle of Man'},
    {name: 'Crosby', country: 'Isle of Man'},
    {name: 'Dalby', country: 'Isle of Man'},
    {name: 'Douglas', country: 'Isle of Man'},
    {name: 'Foxdale', country: 'Isle of Man'},
    {name: 'Laxey', country: 'Isle of Man'},
    {name: 'Onchan', country: 'Isle of Man'},
    {name: 'Peel', country: 'Isle of Man'},
    {name: 'Port Erin', country: 'Isle of Man'},
    {name: 'Port Saint Mary', country: 'Isle of Man'},
    {name: 'Ramsey', country: 'Isle of Man'},
    {name: 'Saint Johns', country: 'Isle of Man'},
    {name: 'Black River', country: 'Jamaica'},
    {name: 'Browns Town', country: 'Jamaica'},
    {name: 'Gordon Town', country: 'Jamaica'},
    {name: 'Gregory Park', country: 'Jamaica'},
    {name: 'Kingston', country: 'Jamaica'},
    {name: 'Mandeville', country: 'Jamaica'},
    {name: 'May Pen', country: 'Jamaica'},
    {name: 'Moneague', country: 'Jamaica'},
    {name: 'Montego Bay', country: 'Jamaica'},
    {name: 'Negril', country: 'Jamaica'},
    {name: 'Ocho Rios', country: 'Jamaica'},
    {name: 'Old Harbour', country: 'Jamaica'},
    {name: 'Port Maria', country: 'Jamaica'},
    {name: 'Portland Cottage', country: 'Jamaica'},
    {name: 'Portmore', country: 'Jamaica'},
    {name: 'Runaway Bay', country: 'Jamaica'},
    {name: 'Spanish Town', country: 'Jamaica'},
    {name: 'Dunavo', country: 'Kosovo'},
    {name: 'Ferizaj', country: 'Kosovo'},
    {name: 'Mitrovica', country: 'Kosovo'},
    {name: 'Pristina', country: 'Kosovo'},
    {name: 'Prizren', country: 'Kosovo'},
    {name: 'Abraq Khaytan', country: 'Kuwait'},
    {name: 'Ad Dasmah', country: 'Kuwait'},
    {name: 'Ad Dawhah', country: 'Kuwait'},
    {name: 'Al Ahmadi', country: 'Kuwait'},
    {name: 'Al Farwaniyah', country: 'Kuwait'},
    {name: 'Al Shamiya', country: 'Kuwait'},
    {name: 'Ar Rawdah', country: 'Kuwait'},
    {name: 'As Salimiyah', country: 'Kuwait'},
    {name: 'Ash Shu`aybah', country: 'Kuwait'},
    {name: 'Ash Shuwaykh', country: 'Kuwait'},
    {name: 'Bayan', country: 'Kuwait'},
    {name: 'Hawalli', country: 'Kuwait'},
    {name: 'Janub as Surrah', country: 'Kuwait'},
    {name: 'Kayfan', country: 'Kuwait'},
    {name: 'Kuwait City', country: 'Kuwait'},
    {name: 'Salwa', country: 'Kuwait'},
    {name: 'Aaley', country: 'Lebanon'},
    {name: 'Adma', country: 'Lebanon'},
    {name: 'Ashrafiye', country: 'Lebanon'},
    {name: 'Baabda', country: 'Lebanon'},
    {name: 'Baalbek', country: 'Lebanon'},
    {name: 'Beirut', country: 'Lebanon'},
    {name: 'Broummana', country: 'Lebanon'},
    {name: 'Bsalim', country: 'Lebanon'},
    {name: 'Chekka', country: 'Lebanon'},
    {name: 'Dbaiye', country: 'Lebanon'},
    {name: 'Dik el Mehdi', country: 'Lebanon'},
    {name: 'Halba', country: 'Lebanon'},
    {name: 'Hboub', country: 'Lebanon'},
    {name: 'Sarba', country: 'Lebanon'},
    {name: 'Sidon', country: 'Lebanon'},
    {name: 'Tripoli', country: 'Lebanon'},
    {name: 'Yanar', country: 'Lebanon'},
    {name: 'Zgharta', country: 'Lebanon'},
    {name: 'Benghazi', country: 'Libya'},
    {name: 'Misratah', country: 'Libya'},
    {name: 'Sabha', country: 'Libya'},
    {name: 'Tripoli', country: 'Libya'},
    {name: 'Zliten', country: 'Libya'},
    {name: 'Balzers', country: 'Liechtenstein'},
    {name: 'Bendern', country: 'Liechtenstein'},
    {name: 'Eschen', country: 'Liechtenstein'},
    {name: 'Gamprin', country: 'Liechtenstein'},
    {name: 'Mauren', country: 'Liechtenstein'},
    {name: 'Nendeln', country: 'Liechtenstein'},
    {name: 'Planken', country: 'Liechtenstein'},
    {name: 'Ruggell', country: 'Liechtenstein'},
    {name: 'Schaan', country: 'Liechtenstein'},
    {name: 'Schaanwald', country: 'Liechtenstein'},
    {name: 'Schellenberg', country: 'Liechtenstein'},
    {name: 'Triesen', country: 'Liechtenstein'},
    {name: 'Triesenberg', country: 'Liechtenstein'},
    {name: 'Vaduz', country: 'Liechtenstein'},
    {name: 'Ambanja', country: 'Madagascar'},
    {name: 'Antananarivo', country: 'Madagascar'},
    {name: 'Antsirabe', country: 'Madagascar'},
    {name: 'Antsiranana', country: 'Madagascar'},
    {name: 'Fianarantsoa', country: 'Madagascar'},
    {name: 'Toamasina', country: 'Madagascar'},
    {name: 'Toliara', country: 'Madagascar'},
    {name: 'Case-Pilote', country: 'Martinique'},
    {name: 'Ducos', country: 'Martinique'},
    {name: 'Fort-de-France', country: 'Martinique'},
    {name: 'Le Carbet', country: 'Martinique'},
    {name: 'Le Diamant', country: 'Martinique'},
    {name: 'Le Francois', country: 'Martinique'},
    {name: 'Le Gros-Morne', country: 'Martinique'},
    {name: 'Le Lamentin', country: 'Martinique'},
    {name: 'Le Morne-Rouge', country: 'Martinique'},
    {name: 'Le Robert', country: 'Martinique'},
    {name: 'Les Trois-Ilets', country: 'Martinique'},
    {name: 'Riviere-Salee', country: 'Martinique'},
    {name: 'Saint-Esprit', country: 'Martinique'},
    {name: 'Saint-Joseph', country: 'Martinique'},
    {name: 'Sainte-Anne', country: 'Martinique'},
    {name: 'Sainte-Luce', country: 'Martinique'},
    {name: 'Sainte-Marie', country: 'Martinique'},
    {name: 'Schoelcher', country: 'Martinique'},
    {name: 'Beau Bassin', country: 'Mauritius'},
    {name: 'Chemin Grenier', country: 'Mauritius'},
    {name: 'Ebene CyberCity', country: 'Mauritius'},
    {name: 'Floreal', country: 'Mauritius'},
    {name: 'Goodlands', country: 'Mauritius'},
    {name: 'Le Reduit', country: 'Mauritius'},
    {name: 'Port Louis', country: 'Mauritius'},
    {name: 'Port Mathurin', country: 'Mauritius'},
    {name: 'Quatre Bornes', country: 'Mauritius'},
    {name: 'Rose Hill', country: 'Mauritius'},
    {name: 'Saint Jean', country: 'Mauritius'},
    {name: 'Tamarin', country: 'Mauritius'},
    {name: 'Vacoas', country: 'Mauritius'},
    {name: 'Bandaboa', country: 'Mayotte'},
    {name: 'Chiconi', country: 'Mayotte'},
    {name: 'Combani', country: 'Mayotte'},
    {name: 'Dzaoudzi', country: 'Mayotte'},
    {name: 'Dzoumonye', country: 'Mayotte'},
    {name: 'Koungou', country: 'Mayotte'},
    {name: 'Mamoudzou', country: 'Mayotte'},
    {name: 'Ouangani', country: 'Mayotte'},
    {name: 'Pamandzi', country: 'Mayotte'},
    {name: 'Sada', country: 'Mayotte'},
    {name: 'Tsingoni', country: 'Mayotte'},
    {name: 'Tsoundzou 1', country: 'Mayotte'},
    {name: 'Budva', country: 'Montenegro'},
    {name: 'Crna Gora', country: 'Montenegro'},
    {name: 'Herceg Novi', country: 'Montenegro'},
    {name: 'Igalo', country: 'Montenegro'},
    {name: 'Kotor', country: 'Montenegro'},
    {name: 'Niksic', country: 'Montenegro'},
    {name: 'Pljevlja', country: 'Montenegro'},
    {name: 'Podgorica', country: 'Montenegro'},
    {name: 'Stari Bar', country: 'Montenegro'},
    {name: 'Ulcinj', country: 'Montenegro'},
    {name: 'Beira', country: 'Mozambique'},
    {name: 'Maputo', country: 'Mozambique'},
    {name: 'Matola', country: 'Mozambique'},
    {name: 'Mozambique', country: 'Mozambique'},
    {name: 'Nampula', country: 'Mozambique'},
    {name: 'Pemba', country: 'Mozambique'},
    {name: 'Quelimane', country: 'Mozambique'},
    {name: 'Tete', country: 'Mozambique'},
    {name: 'Hlaing', country: 'Myanmar [Burma]'},
    {name: 'Inya', country: 'Myanmar [Burma]'},
    {name: 'Kyauktada', country: 'Myanmar [Burma]'},
    {name: 'Mandalay', country: 'Myanmar [Burma]'},
    {name: 'Wagan', country: 'Myanmar [Burma]'},
    {name: 'Yangon', country: 'Myanmar [Burma]'},
    {name: 'Etunda', country: 'Namibia'},
    {name: 'Grootfontein', country: 'Namibia'},
    {name: 'Katima Mulilo', country: 'Namibia'},
    {name: 'Keetmanshoop', country: 'Namibia'},
    {name: 'Mpapuka', country: 'Namibia'},
    {name: 'Olympia', country: 'Namibia'},
    {name: 'Ondangwa', country: 'Namibia'},
    {name: 'Ongwediva', country: 'Namibia'},
    {name: 'Oranjemund', country: 'Namibia'},
    {name: 'Oshakati', country: 'Namibia'},
    {name: 'Otjiwarongo', country: 'Namibia'},
    {name: 'Outapi', country: 'Namibia'},
    {name: 'Swakopmund', country: 'Namibia'},
    {name: 'Tsumeb', country: 'Namibia'},
    {name: 'Walvis Bay', country: 'Namibia'},
    {name: 'Windhoek', country: 'Namibia'},
    {name: 'Bharatpur', country: 'Nepal'},
    {name: 'Jawlakhel', country: 'Nepal'},
    {name: 'Kathmandu', country: 'Nepal'},
    {name: 'Lumbini', country: 'Nepal'},
    {name: 'Palpa', country: 'Nepal'},
    {name: 'Patan', country: 'Nepal'},
    {name: 'Dumbea', country: 'New Caledonia'},
    {name: 'Mont-Dore', country: 'New Caledonia'},
    {name: 'Noumea', country: 'New Caledonia'},
    {name: 'Nouville', country: 'New Caledonia'},
    {name: 'Paita', country: 'New Caledonia'},
    {name: 'Bluefields', country: 'Nicaragua'},
    {name: 'Chinandega', country: 'Nicaragua'},
    {name: 'El Panama', country: 'Nicaragua'},
    {name: 'Esteli', country: 'Nicaragua'},
    {name: 'Granada', country: 'Nicaragua'},
    {name: 'Jinotega', country: 'Nicaragua'},
    {name: 'Los Arados', country: 'Nicaragua'},
    {name: 'Managua', country: 'Nicaragua'},
    {name: 'Masaya', country: 'Nicaragua'},
    {name: 'Matagalpa', country: 'Nicaragua'},
    {name: 'Ocotal', country: 'Nicaragua'},
    {name: 'Rivas', country: 'Nicaragua'},
    {name: 'San Juan del Sur', country: 'Nicaragua'},
    {name: 'Al Sohar', country: 'Oman'},
    {name: 'Muscat', country: 'Oman'},
    {name: 'Nizwa', country: 'Oman'},
    {name: 'Ruwi', country: 'Oman'},
    {name: 'Saham', country: 'Oman'},
    {name: 'Salalah', country: 'Oman'},
    {name: 'Samad', country: 'Oman'},
    {name: 'Al Mawasi', country: 'Palestine'},
    {name: 'Bethlehem', country: 'Palestine'},
    {name: 'Gaza', country: 'Palestine'},
    {name: 'Hebron', country: 'Palestine'},
    {name: 'Jenin', country: 'Palestine'},
    {name: 'Jericho', country: 'Palestine'},
    {name: 'Nablus', country: 'Palestine'},
    {name: 'Ramallah', country: 'Palestine'},
    {name: 'Anenii Noi', country: 'Republic of Moldova'},
    {name: 'Briceni', country: 'Republic of Moldova'},
    {name: 'Cahul', country: 'Republic of Moldova'},
    {name: 'Calarasi', country: 'Republic of Moldova'},
    {name: 'Ciorescu', country: 'Republic of Moldova'},
    {name: 'Cojusna', country: 'Republic of Moldova'},
    {name: 'Comrat', country: 'Republic of Moldova'},
    {name: 'Drochia', country: 'Republic of Moldova'},
    {name: 'Durlesti', country: 'Republic of Moldova'},
    {name: 'Ialoveni', country: 'Republic of Moldova'},
    {name: 'Magdacesti', country: 'Republic of Moldova'},
    {name: 'Nisporeni', country: 'Republic of Moldova'},
    {name: 'Orhei', country: 'Republic of Moldova'},
    {name: 'Soroca', country: 'Republic of Moldova'},
    {name: 'Straseni', country: 'Republic of Moldova'},
    {name: 'Tighina', country: 'Republic of Moldova'},
    {name: 'Tiraspol', country: 'Republic of Moldova'},
    {name: 'Voinescu', country: 'Republic of Moldova'},
    {name: 'Vulcanesti', country: 'Republic of Moldova'},
    {name: 'Anse La Raye', country: 'Saint Lucia'},
    {name: 'Castries', country: 'Saint Lucia'},
    {name: 'Choiseul', country: 'Saint Lucia'},
    {name: 'Dauphin', country: 'Saint Lucia'},
    {name: 'Gros Islet', country: 'Saint Lucia'},
    {name: 'Vieux Fort', country: 'Saint Lucia'},
    {name: 'Acquaviva', country: 'San Marino'},
    {name: 'Falciano', country: 'San Marino'},
    {name: 'Fiorentino', country: 'San Marino'},
    {name: 'San Marino', country: 'San Marino'},
    {name: 'Serravalle', country: 'San Marino'},
    {name: 'Boussinki', country: 'Senegal'},
    {name: 'Camberene', country: 'Senegal'},
    {name: 'Dakar', country: 'Senegal'},
    {name: 'Dodji', country: 'Senegal'},
    {name: 'Guediawaye', country: 'Senegal'},
    {name: 'Kaolack', country: 'Senegal'},
    {name: 'Kedougou', country: 'Senegal'},
    {name: 'Louga', country: 'Senegal'},
    {name: 'Madina Kokoun', country: 'Senegal'},
    {name: 'Saint-Louis', country: 'Senegal'},
    {name: 'Sama', country: 'Senegal'},
    {name: 'Tanaf', country: 'Senegal'},
    {name: 'Kassala', country: 'Sudan'},
    {name: 'Khartoum', country: 'Sudan'},
    {name: 'Nyala', country: 'Sudan'},
    {name: 'Shendi', country: 'Sudan'},
    {name: 'Thabit', country: 'Sudan'},
    {name: 'Umm Durman', country: 'Sudan'},
    {name: 'Botopasi', country: 'Suriname'},
    {name: 'Brownsweg', country: 'Suriname'},
    {name: 'Friendship', country: 'Suriname'},
    {name: 'Groningen', country: 'Suriname'},
    {name: 'Moengo', country: 'Suriname'},
    {name: 'Nieuw Amsterdam', country: 'Suriname'},
    {name: 'Onverwacht', country: 'Suriname'},
    {name: 'Paramaribo', country: 'Suriname'},
    {name: 'Totness', country: 'Suriname'},
    {name: 'Kwaluseni', country: 'Swaziland'},
    {name: 'Lobamba', country: 'Swaziland'},
    {name: 'Manzini', country: 'Swaziland'},
    {name: 'Mbabane', country: 'Swaziland'},
    {name: 'Piggs Peak', country: 'Swaziland'},
    {name: 'Arusha', country: 'Tanzania'},
    {name: 'Bukoba', country: 'Tanzania'},
    {name: 'Dar es Salaam', country: 'Tanzania'},
    {name: 'Dodoma', country: 'Tanzania'},
    {name: 'Morogoro', country: 'Tanzania'},
    {name: 'Mwanza', country: 'Tanzania'},
    {name: 'Njombe', country: 'Tanzania'},
    {name: 'Raha', country: 'Tanzania'},
    {name: 'Tanga', country: 'Tanzania'},
    {name: 'Zanzibar', country: 'Tanzania'},
    {name: 'Ariana', country: 'Tunisia'},
    {name: 'Beja', country: 'Tunisia'},
    {name: 'Gafsa', country: 'Tunisia'},
    {name: 'Hammamet', country: 'Tunisia'},
    {name: 'Le Bardo', country: 'Tunisia'},
    {name: 'Manouba', country: 'Tunisia'},
    {name: 'Monastir', country: 'Tunisia'},
    {name: 'Rades', country: 'Tunisia'},
    {name: 'Sfax', country: 'Tunisia'},
    {name: 'Sidi Bouzid', country: 'Tunisia'},
    {name: 'Sousse', country: 'Tunisia'},
    {name: 'Tunis', country: 'Tunisia'},
    {name: 'Charlotte Amalie', country: 'U.S. Virgin Islands'},
    {name: 'Christiansted', country: 'U.S. Virgin Islands'},
    {name: 'Frederiksted', country: 'U.S. Virgin Islands'},
    {name: 'Kingshill', country: 'U.S. Virgin Islands'},
    {name: 'St John Island', country: 'U.S. Virgin Islands'},
    {name: 'Abu Dhabi', country: 'United Arab Emirates'},
    {name: 'Al Ain', country: 'United Arab Emirates'},
    {name: 'Al Khan', country: 'United Arab Emirates'},
    {name: 'Ar Ruways', country: 'United Arab Emirates'},
    {name: 'As Satwah', country: 'United Arab Emirates'},
    {name: 'Dayrah', country: 'United Arab Emirates'},
    {name: 'Dubai', country: 'United Arab Emirates'},
    {name: 'Fujairah', country: 'United Arab Emirates'},
    {name: 'Ras al-Khaimah', country: 'United Arab Emirates'},
    {name: 'Sharjah', country: 'United Arab Emirates'},
    {name: 'Barra de Carrasco', country: 'Uruguay'},
    {name: 'Canelones', country: 'Uruguay'},
    {name: 'Colonia del Sacramento', country: 'Uruguay'},
    {name: 'Durazno', country: 'Uruguay'},
    {name: 'Florida', country: 'Uruguay'},
    {name: 'La Floresta', country: 'Uruguay'},
    {name: 'La Paz', country: 'Uruguay'},
    {name: 'Las Piedras', country: 'Uruguay'},
    {name: 'Maldonado', country: 'Uruguay'},
    {name: 'Mercedes', country: 'Uruguay'},
    {name: 'Montevideo', country: 'Uruguay'},
    {name: 'Punta del Este', country: 'Uruguay'},
    {name: 'Salto', country: 'Uruguay'},
    {name: 'San Carlos', country: 'Uruguay'},
    {name: 'Toledo', country: 'Uruguay'},
    {name: 'Union', country: 'Uruguay'},
    {name: 'Kalomo', country: 'Zambia'},
    {name: 'Kitwe', country: 'Zambia'},
    {name: 'Livingstone', country: 'Zambia'},
    {name: 'Lusaka', country: 'Zambia'},
    {name: 'Macha', country: 'Zambia'},
    {name: 'Mumbwa', country: 'Zambia'},
    {name: 'Ndola', country: 'Zambia'},
    {name: 'Siavonga', country: 'Zambia'},
    {name: 'Solwezi', country: 'Zambia'},
    {name: 'Bulawayo', country: 'Zimbabwe'},
    {name: 'Chinhoyi', country: 'Zimbabwe'},
    {name: 'Greendale', country: 'Zimbabwe'},
    {name: 'Gwanda', country: 'Zimbabwe'},
    {name: 'Harare', country: 'Zimbabwe'},
    {name: 'Kwekwe', country: 'Zimbabwe'},
    {name: 'Mufakose', country: 'Zimbabwe'},
    {name: 'Mutare', country: 'Zimbabwe'},
    {name: 'Victoria Falls', country: 'Zimbabwe'},   
  ];

function normalize(array){
    const newArray = array;
    const resultObject = newArray.map(item => new Object({name: item.name.toLowerCase().replace(/\s/g, ''), country: item.country.toLowerCase().replace(/\s/g, '')}))
    .reduce((accumulator, item) => {
        if (_.get(accumulator, item.country) === undefined) {
          accumulator[item.country] = [];
        }
        if(!accumulator[item.country].includes(item.name)){
            accumulator[item.country].push(item.name);
        }
        return accumulator;
      }, {});
    return resultObject;
}

console.log(normalize(countries));