import _ from 'lodash';

const countries = [
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'Miami', country: 'usa' },
    { name: 'kYiv', country: '  ukraInE' },
    { name: 'Odessa ', country: 'ukraInE' },
    { name: 'AlBuQErqUe', country: 'usa' },
    { name: 'kRaKow', country: '  PolaNd' },
    { name: 'GdYnIa ', country: 'poLand' },
    { name: 'GdYnIa ', country: 'poLand' },
    
  ];

function normalize(array){
    const newArray = array;
    const resultObject = newArray.map(item => new Object({name: item.name.toLowerCase().replace(/\s/g, ''), country: item.country.toLowerCase().replace(/\s/g, '')}))
    .reduce((accumulator, item) => {
        if (_.get(accumulator, item.country) === undefined) {
          accumulator[item.country] = [];
        }
        if(!accumulator[item.country].includes(item.name)){
            accumulator[item.country].push(item.name);
        }
        return accumulator;
      }, {});
    return resultObject;
}

console.log(normalize(countries));